version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playmais-shop
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/playmaisshop
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17-alpine
    container_name: playmais-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playmaisshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
